name: flutter_dasher
description: A new Flutter onboarding project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.4
  flutter_inappwebview: ^5.4.3+7
  flutter_svg: ^1.1.0
  freezed: ^2.0.3+1
  get_it: ^7.2.0
  riverpod: ^1.0.3
  dio: ^4.0.6
  flutter_secure_storage: ^5.0.2
  json_serializable: ^6.2.0
  japx: ^2.0.4
  loggy: ^2.0.1+1
  hooks_riverpod: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen: ^4.3.0
  build_runner: ^2.1.11

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true