name: flutter_dasher
description: A new Flutter onboarding project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.4
  flutter_inappwebview: ^5.4.3+7
  flutter_svg: ^1.1.0
  get_it: ^7.2.0
  riverpod: ^1.0.3
  dio: ^4.0.6
  flutter_secure_storage: ^5.0.2
  json_serializable: ^6.2.0
  japx: ^2.0.4
  loggy: ^2.0.1+1
  hooks_riverpod: ^1.0.4
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.3+1
  flutter_gen_runner: ^4.3.0
  flutter_loggy: ^2.0.1
  freezed_annotation: ^2.0.3
  cached_network_image: ^3.2.1
  twitter_oauth2_pkce: ^0.3.0
  twitter_api_v2: ^2.8.1
  intl: ^0.17.0

dependency_overrides:
  flutter_web_auth:
    git:
      url: https://github.com/noga-dev/flutter_web_auth
      ref: a49488592f9eeeec3c75ae9335ed51ae84f2a2b0
  twitter_oauth2_pkce:
    git:
      url: https://github.com/twitter-dart/twitter-oauth2-pkce.git
      ref: 65411f5ab24a9bbdf5b8904fa93f87c83cce30cb

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen: ^4.3.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/

flutter_icons:
  image_path: 'assets/app_icons/app_icon.png'
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#1DA1F2"
  image: assets/images/splash_center_logo.png